/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTestMiscComplex"
 * 	found in "/home/intest/hozon/asnEDc/asn1c-0.9.28/tests/33-misc-OK.asn1"
 * 	`asn1c -S /home/intest/hozon/asnEDc/asn1c-0.9.28/skeletons -Wdebug-compiler`
 */

#ifndef	_Label_H_
#define	_Label_H_


#include <asn_application.h>

/* Including external dependencies */
#include <UTF8String.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Label */
typedef UTF8String_t	 Label_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Label;
asn_struct_free_f Label_free;
asn_struct_print_f Label_print;
asn_constr_check_f Label_constraint;
ber_type_decoder_f Label_decode_ber;
der_type_encoder_f Label_encode_der;
xer_type_decoder_f Label_decode_xer;
xer_type_encoder_f Label_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Label_H_ */
#include <asn_internal.h>
