/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleRedefineType"
 * 	found in "/home/intest/hozon/asnEDc/asn1c-0.9.28/tests/46-redefine-OK.asn1"
 * 	`asn1c -S /home/intest/hozon/asnEDc/asn1c-0.9.28/skeletons -Wdebug-compiler`
 */

#ifndef	_ConstructedType_H_
#define	_ConstructedType_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PrimitiveType.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ConstructedType */
typedef struct ConstructedType {
	PrimitiveType_t	 field;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ConstructedType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ConstructedType;

#ifdef __cplusplus
}
#endif

#endif	/* _ConstructedType_H_ */
#include <asn_internal.h>
