/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTestSameNames"
 * 	found in "/home/intest/hozon/asnEDc/asn1c-0.9.28/tests/72-same-names-OK.asn1"
 * 	`asn1c -S /home/intest/hozon/asnEDc/asn1c-0.9.28/skeletons -Wdebug-compiler -fcompound-names`
 */

#ifndef	_Type1_H_
#define	_Type1_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Type1__one_name_PR {
	Type1__one_name_PR_NOTHING,	/* No components present */
	Type1__one_name_PR_another_name
} Type1__one_name_PR;

/* Type1 */
typedef struct Type1 {
	struct Type1__one_name {
		Type1__one_name_PR present;
		union Type1__one_name_u {
			struct Type1__one_name__another_name {
				long	 a;
				long	 b;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} another_name;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} one_name;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Type1_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Type1;

#ifdef __cplusplus
}
#endif

#endif	/* _Type1_H_ */
#include <asn_internal.h>
