/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTestSameNames"
 * 	found in "/home/intest/hozon/asnEDc/asn1c-0.9.28/tests/72-same-names-OK.asn1"
 * 	`asn1c -S /home/intest/hozon/asnEDc/asn1c-0.9.28/skeletons -Wdebug-compiler -fcompound-names`
 */

#include "Type1.h"

static asn_TYPE_member_t asn_MBR_another_name_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Type1__one_name__another_name, a),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"a"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Type1__one_name__another_name, b),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"b"
		},
};
static const ber_tlv_tag_t asn_DEF_another_name_tags_3[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_another_name_tag2el_3[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 1 }, /* a */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, -1, 0 } /* b */
};
static asn_SEQUENCE_specifics_t asn_SPC_another_name_specs_3 = {
	sizeof(struct Type1__one_name__another_name),
	offsetof(struct Type1__one_name__another_name, _asn_ctx),
	asn_MAP_another_name_tag2el_3,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_another_name_3 = {
	"another-name",
	"another-name",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_another_name_tags_3,
	sizeof(asn_DEF_another_name_tags_3)
		/sizeof(asn_DEF_another_name_tags_3[0]), /* 1 */
	asn_DEF_another_name_tags_3,	/* Same as above */
	sizeof(asn_DEF_another_name_tags_3)
		/sizeof(asn_DEF_another_name_tags_3[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_another_name_3,
	2,	/* Elements count */
	&asn_SPC_another_name_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_one_name_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Type1__one_name, choice.another_name),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_another_name_3,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"another-name"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_one_name_tag2el_2[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 0 } /* another-name */
};
static asn_CHOICE_specifics_t asn_SPC_one_name_specs_2 = {
	sizeof(struct Type1__one_name),
	offsetof(struct Type1__one_name, _asn_ctx),
	offsetof(struct Type1__one_name, present),
	sizeof(((struct Type1__one_name *)0)->present),
	asn_MAP_one_name_tag2el_2,
	1,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_one_name_2 = {
	"one-name",
	"one-name",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_one_name_2,
	1,	/* Elements count */
	&asn_SPC_one_name_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_Type1_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Type1, one_name),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_one_name_2,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"one-name"
		},
};
static const ber_tlv_tag_t asn_DEF_Type1_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Type1_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 0 } /* another-name */
};
static asn_SEQUENCE_specifics_t asn_SPC_Type1_specs_1 = {
	sizeof(struct Type1),
	offsetof(struct Type1, _asn_ctx),
	asn_MAP_Type1_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_Type1 = {
	"Type1",
	"Type1",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_Type1_tags_1,
	sizeof(asn_DEF_Type1_tags_1)
		/sizeof(asn_DEF_Type1_tags_1[0]), /* 1 */
	asn_DEF_Type1_tags_1,	/* Same as above */
	sizeof(asn_DEF_Type1_tags_1)
		/sizeof(asn_DEF_Type1_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_Type1_1,
	1,	/* Elements count */
	&asn_SPC_Type1_specs_1	/* Additional specs */
};

