/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleLAPStorage"
 * 	found in "/home/intest/hozon/asnEDc/asn1c-0.9.28/tests/42-real-life-OK.asn1"
 * 	`asn1c -S /home/intest/hozon/asnEDc/asn1c-0.9.28/skeletons -Wdebug-compiler`
 */

#ifndef	_LogLine_H_
#define	_LogLine_H_


#include <asn_application.h>

/* Including external dependencies */
#include <IA5String.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct VariablePartSet;

/* LogLine */
typedef struct LogLine {
	IA5String_t	 line_digest;
	struct varsets {
		A_SEQUENCE_OF(struct VariablePartSet) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} varsets;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LogLine_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LogLine;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "VariablePartSet.h"

#endif	/* _LogLine_H_ */
#include <asn_internal.h>
