/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "HOZON"
 * 	found in "HOZON_PRIV_v1.0.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_CertificateDownloadReqInfo_H_
#define	_CertificateDownloadReqInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CertificateDownloadReqInfo */
typedef struct CertificateDownloadReqInfo {
	long	 mid;
	long	 eventId;
	long	 cerType;
	long	 infoListLength;
	OCTET_STRING_t	 infoList;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CertificateDownloadReqInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CertificateDownloadReqInfo;

#ifdef __cplusplus
}
#endif

#endif	/* _CertificateDownloadReqInfo_H_ */
#include <asn_internal.h>
