/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "HOZON"
 * 	found in "HOZON_PRIV_v1.0.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_CertificateDownloadStatusInfo_H_
#define	_CertificateDownloadStatusInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <BOOLEAN.h>
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CertificateDownloadStatusInfo */
typedef struct CertificateDownloadStatusInfo {
	long	 mid;
	long	 eventId;
	long	 certType;
	BOOLEAN_t	 result;
	long	*failureType	/* OPTIONAL */;
	long	 infoListLength;
	OCTET_STRING_t	 infoList;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CertificateDownloadStatusInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CertificateDownloadStatusInfo;

#ifdef __cplusplus
}
#endif

#endif	/* _CertificateDownloadStatusInfo_H_ */
#include <asn_internal.h>
