/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "HOZON"
 * 	found in "HOZON_PRIV_v1.0.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_DiagnosticLogFailure_H_
#define	_DiagnosticLogFailure_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <BOOLEAN.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DiagnosticLogFailure */
typedef struct DiagnosticLogFailure {
	long	 ecuType;
	BOOLEAN_t	 result;
	long	*failureType	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DiagnosticLogFailure_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DiagnosticLogFailure;

#ifdef __cplusplus
}
#endif

#endif	/* _DiagnosticLogFailure_H_ */
#include <asn_internal.h>
