/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "HOZON"
 * 	found in "HOZON_PRIV_v1.0.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_DiagnosticReqInfo_H_
#define	_DiagnosticReqInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct DiagCommand;

/* DiagnosticReqInfo */
typedef struct DiagnosticReqInfo {
	struct diagCommand {
		A_SEQUENCE_OF(struct DiagCommand) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} diagCommand;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DiagnosticReqInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DiagnosticReqInfo;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "DiagCommand.h"

#endif	/* _DiagnosticReqInfo_H_ */
#include <asn_internal.h>
