/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "HOZON"
 * 	found in "HOZON_PRIV_v1.0.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_DiagnosticLogRespInfo_H_
#define	_DiagnosticLogRespInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct DiagnosticLogFailure;

/* DiagnosticLogRespInfo */
typedef struct DiagnosticLogRespInfo {
	struct failureList {
		A_SEQUENCE_OF(struct DiagnosticLogFailure) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *failureList;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DiagnosticLogRespInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DiagnosticLogRespInfo;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "DiagnosticLogFailure.h"

#endif	/* _DiagnosticLogRespInfo_H_ */
#include <asn_internal.h>
