/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "HOZON"
 * 	found in "HOZON_PRIV_v1.0.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_LogAcquisitionResInfo_H_
#define	_LogAcquisitionResInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <BOOLEAN.h>
#include <IA5String.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LogAcquisitionResInfo */
typedef struct LogAcquisitionResInfo {
	long	 logType;
	BOOLEAN_t	 result;
	long	*failureType	/* OPTIONAL */;
	IA5String_t	*fileName	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LogAcquisitionResInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LogAcquisitionResInfo;

#ifdef __cplusplus
}
#endif

#endif	/* _LogAcquisitionResInfo_H_ */
#include <asn_internal.h>
