/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleRecursion"
 * 	found in "/home/intest/hozon/asnEDc/asn1c-0.9.28/tests/43-recursion-OK.asn1"
 * 	`asn1c -S /home/intest/hozon/asnEDc/asn1c-0.9.28/skeletons -Wdebug-compiler`
 */

#ifndef	_Test_structure_3_H_
#define	_Test_structure_3_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SET.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */

/*
 * Method of determining the components presence
 */
typedef enum Test_structure_3_PR {
	Test_structure_3_PR_m1,	/* Member m1 is present */
} Test_structure_3_PR;

/* Forward declarations */
struct Test_structure_2;

/* Test-structure-3 */
typedef struct Test_structure_3 {
	struct Test_structure_2	*m1	/* OPTIONAL */;
	
	/* Presence bitmask: ASN_SET_ISPRESENT(pTest_structure_3, Test_structure_3_PR_x) */
	unsigned int _presence_map
		[((1+(8*sizeof(unsigned int))-1)/(8*sizeof(unsigned int)))];
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Test_structure_3_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Test_structure_3;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Test-structure-2.h"

#endif	/* _Test_structure_3_H_ */
#include <asn_internal.h>
