/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleSetChoiceExtensibility"
 * 	found in "/home/intest/hozon/asnEDc/asn1c-0.9.28/tests/48-real-life-OK.asn1"
 * 	`asn1c -S /home/intest/hozon/asnEDc/asn1c-0.9.28/skeletons -Wdebug-compiler`
 */

#include "UserIdentifier.h"

static asn_TYPE_member_t asn_MBR_UserIdentifier_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct UserIdentifier, choice.phoneNumber),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_IA5String,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"phoneNumber"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_UserIdentifier_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 0, 0, 0 } /* phoneNumber */
};
static asn_CHOICE_specifics_t asn_SPC_UserIdentifier_specs_1 = {
	sizeof(struct UserIdentifier),
	offsetof(struct UserIdentifier, _asn_ctx),
	offsetof(struct UserIdentifier, present),
	sizeof(((struct UserIdentifier *)0)->present),
	asn_MAP_UserIdentifier_tag2el_1,
	1,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_UserIdentifier = {
	"UserIdentifier",
	"UserIdentifier",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_UserIdentifier_1,
	1,	/* Elements count */
	&asn_SPC_UserIdentifier_specs_1	/* Additional specs */
};

