/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleNestedConstraintsCheck"
 * 	found in "/home/intest/hozon/asnEDc/asn1c-0.9.28/tests/50-constraint-OK.asn1"
 * 	`asn1c -S /home/intest/hozon/asnEDc/asn1c-0.9.28/skeletons -Wdebug-compiler`
 */

#ifndef	_Neither_SIZE_nor_FROM_H_
#define	_Neither_SIZE_nor_FROM_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PER-Visible.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Neither-SIZE-nor-FROM */
typedef PER_Visible_t	 Neither_SIZE_nor_FROM_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Neither_SIZE_nor_FROM;
asn_struct_free_f Neither_SIZE_nor_FROM_free;
asn_struct_print_f Neither_SIZE_nor_FROM_print;
asn_constr_check_f Neither_SIZE_nor_FROM_constraint;
ber_type_decoder_f Neither_SIZE_nor_FROM_decode_ber;
der_type_encoder_f Neither_SIZE_nor_FROM_encode_der;
xer_type_decoder_f Neither_SIZE_nor_FROM_decode_xer;
xer_type_encoder_f Neither_SIZE_nor_FROM_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Neither_SIZE_nor_FROM_H_ */
#include <asn_internal.h>
