/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleNestedConstraintsCheck"
 * 	found in "/home/intest/hozon/asnEDc/asn1c-0.9.28/tests/50-constraint-OK.asn1"
 * 	`asn1c -S /home/intest/hozon/asnEDc/asn1c-0.9.28/skeletons -Wdebug-compiler`
 */

#ifndef	_VisibleIdentifier_H_
#define	_VisibleIdentifier_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Identifier.h"

#ifdef __cplusplus
extern "C" {
#endif

/* VisibleIdentifier */
typedef Identifier_t	 VisibleIdentifier_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VisibleIdentifier;
asn_struct_free_f VisibleIdentifier_free;
asn_struct_print_f VisibleIdentifier_print;
asn_constr_check_f VisibleIdentifier_constraint;
ber_type_decoder_f VisibleIdentifier_decode_ber;
der_type_encoder_f VisibleIdentifier_encode_der;
xer_type_decoder_f VisibleIdentifier_decode_xer;
xer_type_encoder_f VisibleIdentifier_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _VisibleIdentifier_H_ */
#include <asn_internal.h>
