/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTestMisc"
 * 	found in "/home/intest/hozon/asnEDc/asn1c-0.9.28/tests/25-misc-OK.asn1"
 * 	`asn1c -S /home/intest/hozon/asnEDc/asn1c-0.9.28/skeletons -Wdebug-compiler -fwide-types`
 */

#ifndef	_T_H_
#define	_T_H_


#include <asn_application.h>

/* Including external dependencies */
#include <INTEGER.h>
#include <BOOLEAN.h>
#include <NULL.h>
#include <ENUMERATED.h>
#include <OCTET_STRING.h>
#include <VisibleString.h>
#include <BIT_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum d {
	d_a	= 1,
	d_b	= 2
} e_d;

/* T */
typedef struct T {
	INTEGER_t	 a;
	BOOLEAN_t	 b;
	NULL_t	 c;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	ENUMERATED_t	*d;
	OCTET_STRING_t	*e;
	VisibleString_t	*f;
	BIT_STRING_t	*g;
	BIT_STRING_t	*h;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} T_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_d_6;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_T;

#ifdef __cplusplus
}
#endif

#endif	/* _T_H_ */
#include <asn_internal.h>
