/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTestMultipleTags"
 * 	found in "/home/intest/hozon/asnEDc/asn1c-0.9.28/tests/65-multi-tag-OK.asn1"
 * 	`asn1c -S /home/intest/hozon/asnEDc/asn1c-0.9.28/skeletons -Wdebug-compiler`
 */

#ifndef	_T4_H_
#define	_T4_H_


#include <asn_application.h>

/* Including external dependencies */
#include "T5.h"

#ifdef __cplusplus
extern "C" {
#endif

/* T4 */
typedef T5_t	 T4_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_T4;
asn_struct_free_f T4_free;
asn_struct_print_f T4_print;
asn_constr_check_f T4_constraint;
ber_type_decoder_f T4_decode_ber;
der_type_encoder_f T4_encode_der;
xer_type_decoder_f T4_decode_xer;
xer_type_encoder_f T4_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _T4_H_ */
#include <asn_internal.h>
