/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTestMultipleTags"
 * 	found in "/home/intest/hozon/asnEDc/asn1c-0.9.28/tests/65-multi-tag-OK.asn1"
 * 	`asn1c -S /home/intest/hozon/asnEDc/asn1c-0.9.28/skeletons -Wdebug-compiler`
 */

#ifndef	_T5_H_
#define	_T5_H_


#include <asn_application.h>

/* Including external dependencies */
#include "T6.h"

#ifdef __cplusplus
extern "C" {
#endif

/* T5 */
typedef T6_t	 T5_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_T5;
asn_struct_free_f T5_free;
asn_struct_print_f T5_print;
asn_constr_check_f T5_constraint;
ber_type_decoder_f T5_decode_ber;
der_type_encoder_f T5_encode_der;
xer_type_decoder_f T5_decode_xer;
xer_type_encoder_f T5_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _T5_H_ */
#include <asn_internal.h>
