/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTestMultipleTags"
 * 	found in "/home/intest/hozon/asnEDc/asn1c-0.9.28/tests/65-multi-tag-OK.asn1"
 * 	`asn1c -S /home/intest/hozon/asnEDc/asn1c-0.9.28/skeletons -Wdebug-compiler`
 */

#include "T6.h"

int
T6_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeReal.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeReal,
 * so here we adjust the DEF accordingly.
 */
static void
T6_1_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeReal.free_struct;
	td->print_struct   = asn_DEF_NativeReal.print_struct;
	td->check_constraints = asn_DEF_NativeReal.check_constraints;
	td->ber_decoder    = asn_DEF_NativeReal.ber_decoder;
	td->der_encoder    = asn_DEF_NativeReal.der_encoder;
	td->xer_decoder    = asn_DEF_NativeReal.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeReal.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeReal.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeReal.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeReal.per_constraints;
	td->elements       = asn_DEF_NativeReal.elements;
	td->elements_count = asn_DEF_NativeReal.elements_count;
	td->specifics      = asn_DEF_NativeReal.specifics;
}

void
T6_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	T6_1_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

int
T6_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	T6_1_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

asn_dec_rval_t
T6_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	T6_1_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

asn_enc_rval_t
T6_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	T6_1_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

asn_dec_rval_t
T6_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	T6_1_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

asn_enc_rval_t
T6_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	T6_1_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static const ber_tlv_tag_t asn_DEF_T6_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (9 << 2))
};
asn_TYPE_descriptor_t asn_DEF_T6 = {
	"T6",
	"T6",
	T6_free,
	T6_print,
	T6_constraint,
	T6_decode_ber,
	T6_encode_der,
	T6_decode_xer,
	T6_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_T6_tags_1,
	sizeof(asn_DEF_T6_tags_1)
		/sizeof(asn_DEF_T6_tags_1[0]), /* 1 */
	asn_DEF_T6_tags_1,	/* Same as above */
	sizeof(asn_DEF_T6_tags_1)
		/sizeof(asn_DEF_T6_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	0, 0,	/* No members */
	0	/* No specifics */
};

