/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTestMultipleTags"
 * 	found in "/home/intest/hozon/asnEDc/asn1c-0.9.28/tests/65-multi-tag-OK.asn1"
 * 	`asn1c -S /home/intest/hozon/asnEDc/asn1c-0.9.28/skeletons -Wdebug-compiler`
 */

#ifndef	_Ts_H_
#define	_Ts_H_


#include <asn_application.h>

/* Including external dependencies */
#include "T2.h"
#include "T3.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Ts */
typedef struct Ts {
	T2_t	 m1;
	T3_t	*m2	/* OPTIONAL */;
	T3_t	 m3;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ts_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Ts;

#ifdef __cplusplus
}
#endif

#endif	/* _Ts_H_ */
#include <asn_internal.h>
