/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleNestedSequenceOf"
 * 	found in "/home/intest/hozon/asnEDc/asn1c-0.9.28/tests/39-sequence-of-OK.asn1"
 * 	`asn1c -S /home/intest/hozon/asnEDc/asn1c-0.9.28/skeletons -Wdebug-compiler`
 */

#ifndef	_T2_H_
#define	_T2_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include <UTF8String.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* T2 */
typedef struct T2 {
	BOOLEAN_t	 flag;
	UTF8String_t	 str;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} T2_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_T2;

#ifdef __cplusplus
}
#endif

#endif	/* _T2_H_ */
#include <asn_internal.h>
