/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleCircularReferences"
 * 	found in "/home/intest/hozon/asnEDc/asn1c-0.9.28/tests/92-circular-loops-OK.asn1"
 * 	`asn1c -S /home/intest/hozon/asnEDc/asn1c-0.9.28/skeletons -Wdebug-compiler -findirect-choice`
 */

#ifndef	_TypeRef_H_
#define	_TypeRef_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Sequence.h"

#ifdef __cplusplus
extern "C" {
#endif

/* TypeRef */
typedef Sequence_t	 TypeRef_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TypeRef;
asn_struct_free_f TypeRef_free;
asn_struct_print_f TypeRef_print;
asn_constr_check_f TypeRef_constraint;
ber_type_decoder_f TypeRef_decode_ber;
der_type_encoder_f TypeRef_encode_der;
xer_type_decoder_f TypeRef_decode_xer;
xer_type_encoder_f TypeRef_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _TypeRef_H_ */
#include <asn_internal.h>
