/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTestSetOfSimple"
 * 	found in "/home/intest/hozon/asnEDc/asn1c-0.9.28/tests/31-set-of-OK.asn1"
 * 	`asn1c -S /home/intest/hozon/asnEDc/asn1c-0.9.28/skeletons -Wdebug-compiler -fwide-types`
 */

#ifndef	_Forest_H_
#define	_Forest_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SET_OF.h>
#include <constr_SET_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Tree;

/* Forest */
typedef struct Forest {
	A_SET_OF(struct Tree) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Forest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Forest;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Tree.h"

#endif	/* _Forest_H_ */
#include <asn_internal.h>
