/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTestXERDecoding"
 * 	found in "/home/intest/hozon/asnEDc/asn1c-0.9.28/tests/70-xer-test-OK.asn1"
 * 	`asn1c -S /home/intest/hozon/asnEDc/asn1c-0.9.28/skeletons -Wdebug-compiler -fwide-types`
 */

#ifndef	_NamedSetOfEnums_H_
#define	_NamedSetOfEnums_H_


#include <asn_application.h>

/* Including external dependencies */
#include <ENUMERATED.h>
#include <asn_SET_OF.h>
#include <constr_SET_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum name {
	name_one	= 0,
	name_oneMore	= 1
} e_name;

/* NamedSetOfEnums */
typedef struct NamedSetOfEnums {
	A_SET_OF(ENUMERATED_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NamedSetOfEnums_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_name_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_NamedSetOfEnums;

#ifdef __cplusplus
}
#endif

#endif	/* _NamedSetOfEnums_H_ */
#include <asn_internal.h>
