/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTestSetSimple"
 * 	found in "/home/intest/hozon/asnEDc/asn1c-0.9.28/tests/30-set-OK.asn1"
 * 	`asn1c -S /home/intest/hozon/asnEDc/asn1c-0.9.28/skeletons -Wdebug-compiler -fwide-types`
 */

#ifndef	_T_H_
#define	_T_H_


#include <asn_application.h>

/* Including external dependencies */
#include <INTEGER.h>
#include <IA5String.h>
#include <BOOLEAN.h>
#include <constr_SET.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */

/*
 * Method of determining the components presence
 */
typedef enum T_PR {
	T_PR_i,	/* Member i is present */
	T_PR_s,	/* Member s is present */
	T_PR_b,	/* Member b is present */
} T_PR;

/* T */
typedef struct T {
	INTEGER_t	 i;
	IA5String_t	 s;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	BOOLEAN_t	*b;
	
	/* Presence bitmask: ASN_SET_ISPRESENT(pT, T_PR_x) */
	unsigned int _presence_map
		[((3+(8*sizeof(unsigned int))-1)/(8*sizeof(unsigned int)))];
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} T_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_T;

#ifdef __cplusplus
}
#endif

#endif	/* _T_H_ */
#include <asn_internal.h>
