/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTestSetAndUntaggedChoice"
 * 	found in "/home/intest/hozon/asnEDc/asn1c-0.9.28/tests/35-set-choice-OK.asn1"
 * 	`asn1c -S /home/intest/hozon/asnEDc/asn1c-0.9.28/skeletons -Wdebug-compiler`
 */

#ifndef	_Choice_H_
#define	_Choice_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <BIT_STRING.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Choice_PR {
	Choice_PR_NOTHING,	/* No components present */
	Choice_PR_ch_a,
	Choice_PR_ch_b
} Choice_PR;

/* Choice */
typedef struct Choice {
	Choice_PR present;
	union Choice_u {
		OCTET_STRING_t	 ch_a;
		BIT_STRING_t	 ch_b;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Choice_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Choice;

#ifdef __cplusplus
}
#endif

#endif	/* _Choice_H_ */
#include <asn_internal.h>
