/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ModuleTestSetAndUntaggedChoice"
 * 	found in "/home/intest/hozon/asnEDc/asn1c-0.9.28/tests/35-set-choice-OK.asn1"
 * 	`asn1c -S /home/intest/hozon/asnEDc/asn1c-0.9.28/skeletons -Wdebug-compiler`
 */

#ifndef	_OID_H_
#define	_OID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OBJECT_IDENTIFIER.h>
#include <RELATIVE-OID.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum OID_PR {
	OID_PR_NOTHING,	/* No components present */
	OID_PR_oid,
	OID_PR_r_oid
} OID_PR;

/* OID */
typedef struct OID {
	OID_PR present;
	union OID_u {
		OBJECT_IDENTIFIER_t	 oid;
		RELATIVE_OID_t	 r_oid;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} OID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OID;

#ifdef __cplusplus
}
#endif

#endif	/* _OID_H_ */
#include <asn_internal.h>
