/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ModulePERExtensions"
 * 	found in "/home/intest/hozon/asnEDc/asn1c-0.9.28/tests/126-per-extensions-OK.asn1"
 * 	`asn1c -S /home/intest/hozon/asnEDc/asn1c-0.9.28/skeletons -Wdebug-compiler -gen-PER`
 */

#ifndef	_PDU_H_
#define	_PDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include <IA5String.h>
#include "Singleton.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PDU_2;
struct Singleton;

/* PDU */
typedef struct PDU {
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	IA5String_t	*str_o	/* OPTIONAL */;
	IA5String_t	*str_m;
	struct Singleton	*singl;
	struct PDU_2	*pdu_2	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PDU;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PDU-2.h"

#endif	/* _PDU_H_ */
#include <asn_internal.h>
