/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ModulePERExtensions"
 * 	found in "/home/intest/hozon/asnEDc/asn1c-0.9.28/tests/126-per-extensions-OK.asn1"
 * 	`asn1c -S /home/intest/hozon/asnEDc/asn1c-0.9.28/skeletons -Wdebug-compiler -gen-PER`
 */

#ifndef	_Singleton_H_
#define	_Singleton_H_


#include <asn_application.h>

/* Including external dependencies */
#include <IA5String.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Singleton */
typedef struct Singleton {
	IA5String_t	*opt_z	/* DEFAULT z */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Singleton_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Singleton;

#ifdef __cplusplus
}
#endif

#endif	/* _Singleton_H_ */
#include <asn_internal.h>
